controller_manager:
  ros__parameters:
    update_rate: 150

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

#     revolution_3_position_controller:
#       type: forward_position_controller/ForwardPositionController

#     revolution_5_position_controller:
#       type: forward_position_controller/ForwardPositionController

# revolution_3_position_controller:
#   ros__parameters:
#     joints:
#       - revolution_3

# revolution_5_position_controller:
#   ros__parameters:
#     joints:
#       - revolution_5




diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["revolution_3"]
    right_wheel_names: ["revolution_5"]

    wheel_separation: 0.115
    wheel_radius: 0.032

    odom_frame_id: "odom"
    base_frame_id: "base_link"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true

    publish_rate: 150.0
 
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0